### PR TITLE
#398 typescript support

### PR DESCRIPTION
**Pull request by siriwatknp**
@venegasalejandro Oh, wow. This is amazing!

### CODE REVIEW

**Comment by venegasalejandro** [comment]
Thank you!

There are a couple of questions I had with some of the structures through the package, but I don't know the best way to ask them all. It's mainly with SidebarAdapter grabbing variables seemingly from the LayoutContext but some of variables never seem to exist.

I was also going to make another fork and redo the commits with the convention you seem to be doing in the project, but if you don't mind then this fork will do fine.

**Comment by dohomi** [comment]
@siriwatknp is this PR going to be approved? TypeScript support would be amazing

**Comment by lostmarinero** [comment]
+1 for typescript support! Would love to see this added

**Comment by siriwatknp** [comment]
@all-contributors please add @venegasalejandro for code

**Pull request merged**
